[tool.poetry]
name = "aasd"
version = "0.1.0"
description = "Autonomous Administrative System daemon"
authors = ["Jacek 'Szumak' Kotlarski <szumak@virthost.pl>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
jsktoolbox = "^1.0.10"
mako = "^1.3.0"
sqlalchemy = "^2.0.23"
mysql-connector-python = "^8.2.0"
pymysql = "^1.1.0"

[tool.poetry.group.dev.dependencies]
black = "^23.10.1"
pytest = "^7.4.3"
nose = "^1.3.7"
typing-extensions = "^4.8.0"
pycodestyle = "^2.11.1"
pydocstyle = "^6.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
